### PR TITLE
Fix unexpected token * error

### PR DESCRIPTION
**Pull request by tgdev**
Trying to run assemble in my build process gave me the error below. Please resolve ASAP.

/PATH TO PROJECT/node_modules/assemble/node_modules/assemble-core/node_modules/templates/node_modules/engine-cache/node_modules/async-helpers/index.js:243
AsyncHelpers.prototype.resolveId = function*(key) {
                                           ^
SyntaxError: Unexpected token *

### CODE REVIEW

**Comment by doowb** [comment]
This is the syntax for a javascript generator function.

**Comment by doowb** [comment]
@tgdev sorry, I was going to give more details on the other issue you opened but it was just a commit comment 😦 

Javascript generator functions are supported in node >= 4.0. You should upgrade to a newer version of node. We've been using this syntax and a few other es2015 syntaxes throughout the assemble code for a few months now.

**Comment by jonschlinkert** [comment]
> You should upgrade to a newer version of node

this is more of a general recommendation (e.g. not just because of assemble). there were a number of nuisance bugs in node 4.0 that have been fixed, including a bug that effected `util.inhert` etc

**Comment by tgdev** [comment]
Sure that's good in theory but the project Im working on is a legacy
project so upgrading is not an option currently. Thanks anyway :-)

**Pull request closed without merging**
